version: "3.4"
services:
  neo4j:
    build: neo4j
    hostname: neo4j
    environment:
      NEO4J_AUTH: neo4j/test
    ports:
      - 7687:7687
      - 7474:7474

  app:
    build:
      context: ./app
      target: app

    hostname: app
    depends_on:
      - neo4j
      - redis
    links:
      - neo4j
      - redis
    expose:
      - 8080
    environment:
      WAIT_HOSTS: neo4j:7687, redis:6379
      NEO4J_PASSWORD: test

  worker:
    build:
      context: app
      target: worker

    depends_on:
      - redis
      - app
    links:
      - redis
      - neo4j
    environment:
      WAIT_HOSTS: neo4j:7687, redis:6379
      NEO4J_PASSWORD: test

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - 8080:80


  redis:
    image: "redis:alpine"
    hostname: redis
    expose:
      - 6379